# -*- coding: utf-8 -*-
"""Kode A_TreeSearch

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PQ5fx1T5bWdBZATrtvLAI86RaitwJy9q
"""

from queue import PriorityQueue

# Fungsi untuk algoritma A* Tree Search
def a_star_tree_search(graph, start, goal, heuristic):
    frontier = PriorityQueue()  # Antrian prioritas berdasarkan f(n) = g(n) + h(n)
    frontier.put((heuristic[start], 0, start, []))  # (f(n), g(n), node, path)

    while not frontier.empty():
        f_value, g_value, current_node, path = frontier.get()  # Ambil simpul dengan prioritas terendah

        path = path + [current_node]  # Tambahkan simpul ke jalur

        if current_node == goal:
            print("\nSimpul tujuan ditemukan!")
            print("Jalur yang ditemukan:", " → ".join(path))
            print("Total biaya jalur:", g_value)
            return path, g_value

        for neighbor, cost in graph[current_node].items():
            g_new = g_value + cost  # g(n) = g(parent) + cost
            f_new = g_new + heuristic[neighbor]  # f(n) = g(n) + h(n)
            frontier.put((f_new, g_new, neighbor, path))  # Masukkan simpul ke frontier

    print("\nSimpul tujuan tidak ditemukan!")
    return None, float("inf")  # Jika simpul tujuan tidak ditemukan

# Daftar heuristik untuk setiap simpul berdasarkan gambar
heuristic = {
    'S': 6,
    'A': 4,
    'B': 3,
    'C': 3,
    'D': 1,
    'G': 0  # Simpul tujuan memiliki nilai heuristik 0
}

# Graf berbobot dalam bentuk adjacency list berdasarkan gambar
graph = {
    'S': {'A': 3, 'B': 2},
    'A': {'B': 1, 'D': 5},
    'B': {'C': 2, 'D': 3},
    'C': {'G': 4},
    'D': {'G': 1}
}

# Titik awal dan tujuan
start_node = 'S'
goal_node = 'G'

# Panggil fungsi A* Tree Search
a_star_tree_search(graph, start_node, goal_node, heuristic)